### ISSUE TITLE
Add image to leftHandle and rightHandle

### ISSUE THREAD

**Issue by ranjitk-plackal** [TomThorpe/TTRangeSlider#1]
Hello @TomThorpe , how we can add Image to leftHandle and rightHandle for both normal and highligted state.

**Comment by TomThorpe** [comment]
Hi,

It's not possible at the moment, sorry. Maybe I'll add it in the future, or you could add it yourself and submit a pull request? :-)

Tom

**Comment by ranjitk-plackal** [comment]
I will do. Can you give any suggestions on how to do it.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.1.51&pv=8.3]
On Sun, Apr 26, 2015 at 1:11 am, TomThorpe/TTRangeSlider
<reply@reply.github.com>
wrote:
Closed #1 [https://github.com/TomThorpe/TTRangeSlider/issues/1] .

—
Reply to this email directly or view it on GitHub
[https://github.com/TomThorpe/TTRangeSlider/issues/1#event-290056764] .[https://github.com/notifications/beacon/AA74C6k4WvQrrVxY-4R5xPFJpNdBkgxTks5oC-V0gaJpZM4EInqC.gif]

**Comment by TomThorpe** [comment]
There are two properties that the handles exist in, 

```
CALayer *leftHandle
CALayer *rightHandle
```

Basically you'd have to have another few properties that store a UIImage for the handles, then if this image is not nil use the image instead of drawing the circle in the handle's layers. So something like replace

```
self.leftHandle.cornerRadius = 8.0f;
self.leftHandle.backgroundColor = self.tintColor.CGColor;
```
with:
```
self.leftHandle.contents = self.leftHandleImage.CGImage;
``` 

The critical thing would be to make sure this is implemented well with the existing properties and doesn't break backwards compatibility though if I'd be able to merge it in here, although obviously you could fork it and do it however you like otherwise :-)

**Comment by ranjitk-plackal** [comment]
Thanks. I will try to implement.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.1.51&pv=8.3]
On Sun, Apr 26, 2015 at 1:11 am, Tom Thorpe <notifications@github.com> wrote:
Closed #1 [https://github.com/TomThorpe/TTRangeSlider/issues/1] .

—
Reply to this email directly or view it on GitHub
[https://github.com/TomThorpe/TTRangeSlider/issues/1#event-290056764] .[https://github.com/notifications/beacon/AA74C6k4WvQrrVxY-4R5xPFJpNdBkgxTks5oC-V0gaJpZM4EInqC.gif]

**Comment by ranjitk-plackal** [comment]
@TomThorpe , I have not forked, I am just trying to see what all I can do.  I am done with adding image for normal state, and for highlighted state I added image in "- (void)animateHandle:(CALayer*)handle withSelection:(BOOL)selected {"  function.

If their is any other better way, please let me know. Secondly I want to have two slider lines, i.e inner and outerline, so that I can have different colors. How we can do it. Any suggestions.


Regards
Ranjit.

**Comment by TomThorpe** [comment]
Sounds about right. If you want to change how the line looks, just change how `sliderLine` is drawn in the setup part :-)

**Comment by ranjitk-plackal** [comment]
Thanks. Regarding the slider line, I meant I want two colors, one inner and one
outer as its in default UISlider.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.1.51&pv=8.3]
On Sun, Apr 26, 2015 at 6:41 pm, TomThorpe/TTRangeSlider
<reply@reply.github.com>
wrote:
Sounds about right. If you want to change how the line looks, just change how sliderLine is drawn in the setup part :-)

—
Reply to this email directly or view it on GitHub
[https://github.com/TomThorpe/TTRangeSlider/issues/1#issuecomment-96377268] .[https://github.com/notifications/beacon/AA74C3XYo6P2_5O3EIWKY495ePLk6nwzks5oDNuKgaJpZM4EInqC.gif]
