### ISSUE TITLE
UI Feature Request

### ISSUE THREAD

**Issue by guyisra** [TomThorpe/TTRangeSlider#12]
This is not functional but mostly UI - 

Have the range between the min and max to be in a custom color and maybe thicker

**Comment by holgersindbaek** [comment]
+1 Is anyone working on this?!

**Comment by mnurhidayat** [comment]
+1 for this

**Comment by TomThorpe** [comment]
No one is working on this at the moment - but it doesn't seem like it would be too much effort. If anyone wants to take it feel free to mention here and submit a PR when you're done, otherwise I'll try and add this at some point in the future (I can't promise when due to other commitments - sorry!)

**Comment by fiantinangon** [comment]
Hi @TomThorpe  i already add pull request including this UI feature :grinning:

**Comment by TomThorpe** [comment]
I've just had a look at your PR @fiantinangon, thanks for your work on that! After a few changes (if youre able to make them - no pressure! ) I'll be able to get that merged.

For anyone else, you can track that PR in https://github.com/TomThorpe/TTRangeSlider/pull/16

**Comment by gitHendrix** [comment]
Hey @TomThorpe there any update on this feature? Was just looking for a two control slider today and came across this project. And this exact feature request is what i need. Thanks!

**Comment by TomThorpe** [comment]
That PR is merged now thanks to @fiantinangon and @ClaudioTSM :-)
