### ISSUE TITLE
non-linear steps

### ISSUE THREAD

**Issue by guyisra** [TomThorpe/TTRangeSlider#13]
I was trying to figure out how to add this in a PR, but couldn't see where is best

If the min,max is 1 and 100,000,000 and I want to pick a range for 1 to 100, it is hard.

if the steps are not linear or exponential, smaller selected values get a finer resolution than the higher values

similarly, might be also good to input an array of not even steps like [1,12,100,400,1000,10000,123545, 100000] for possible options to choose instead of linear steps or step by 1

**Comment by TomThorpe** [comment]
I do understand times when this would be needed, but for now I dont think I'll be implementing it as it would add too much complexity to a control that I'm trying to keep fairly simple to implement and understand.

Sorry!
