### ISSUE TITLE
Cocoapods, iOS 7 and IBDesignable

### ISSUE THREAD

**Issue by Blackjacx** [TomThorpe/TTRangeSlider#14]
Hey,

due to the issue in cocapods (https://github.com/MuscleRumble/THLabel/issues/28) IBDesignables would not work in projects with iOS Version <= 7. Other projects maintain a branch without IBDesignables integrated. 

Can you pls do the same? The compile error in Interface builder really makes problems :-(

**Comment by TomThorpe** [comment]
Hey, sorry I dont think I'm going to do this right now to keep things neat. 

I think it would be best if you forked it yourself and pointed your podfile to that. Sorry.
