### ISSUE TITLE
Label positions problem

### ISSUE THREAD

**Issue by krychlinski** [TomThorpe/TTRangeSlider#2]
If a range between selectedMinimum and selectedMaximum is very small, labels position are incorrect. This situation happened when I have created cell from a nib with TTRangeSlider with my own minValue, maxValue, selectedMinimum and selectedMaximum. But if the range between selectedMinimum and selectedMaximum are bigger, all is correct.

![incorrect](https://cloud.githubusercontent.com/assets/1332329/7794362/f953e100-02c9-11e5-9e4b-6b9ef184766c.png)
![correct](https://cloud.githubusercontent.com/assets/1332329/7794367/0dbe87c6-02ca-11e5-9a2b-40adb15b0359.png)

**Comment by TomThorpe** [comment]
Hey, yes sorry this is a known issue and something I will try to look into soon

**Comment by pronebird** [comment]
I can confirm the problem persists.

**Comment by mariohahn** [comment]
there is also a Problem with with the Label position if you set disableRange = YES

**Comment by TomThorpe** [comment]
Fixed by #23
