### ISSUE TITLE
Cocoapods version does not have hideLabels

### ISSUE THREAD

**Issue by MoridinBG** [TomThorpe/TTRangeSlider#22]
The release in the podspecs lacks some of the newer features from later commits, such as hideLabels

**Comment by senseluo** [comment]
I have the same issue, looks like cocoapods is not the latest version.

**Comment by senseluo** [comment]
temporary solution
pod "TTRangeSlider", :git => 'https://github.com/TomThorpe/TTRangeSlider.git'

**Comment by Maxatma** [comment]
same as tintColorBetweenHandles property isn't in pod version

**Comment by TomThorpe** [comment]
Yeah, sorry. I haven't updated the version in cocoapods yet. As senseluo said you can directly reference this repo by using his example instead of the usual include to always make sure you get the latest features

**Comment by mixdesign** [comment]
@TomThorpe come on man), go and update cocoapods, please... 5 minutes work. 😉

**Comment by TomThorpe** [comment]
Haha! Ok ok fair enough @mixdesign...done! https://github.com/CocoaPods/Specs/commit/0b2c1e2e765ffd8839d6628f6b77ce267ac6badc
