### ISSUE TITLE
Slider freeze issue.

### ISSUE THREAD

**Issue by BaiXiaoYan** [TomThorpe/TTRangeSlider#24]
Hi.
The Slider control are very useful, and very nice.
But I found an issue.
If I open several viewcontrollers, the slider is working on first viewcontroller without no issue, but on top viewcontroller slider freeze, and animate irregularly.
For example, I push 3 viewcontrollers. then on the first viewcontroller is working fine, but on the third controller is not working well.
Can you fix the issue?
Thanks.

**Comment by chefnobody** [comment]
@BaiXiaoYan It might be helpful to provide a sample project that demonstrates the issue you've found.
