### ISSUE TITLE
Implement intrinsicContentSize

### ISSUE THREAD

**Issue by pronebird** [TomThorpe/TTRangeSlider#3]
It would be good to implement `intrinsicContentSize`. My current use case is self-sizing cells, for the time being I have to manually fix the height of range slider, but I guess control could do that itself.

**Comment by TomThorpe** [comment]
Hey,

I've been using self-sizing cells a lot recently too so you're right this should have definitely been in there :-)

I've implemented it here 28b23dff5d86125e23275bf12afaccafba0d4258 setting the height and left the width undetermined as that's based on preference. The height is also a constant (I don't see much need for it to change), so I guess in reality its the same as adding a height in autolayout, but at least it saves that step.
