### ISSUE TITLE
Color changes when opening action sheet.

### ISSUE THREAD

**Issue by codiophile** [TomThorpe/TTRangeSlider#30]
I am using the slider in a view that has an action sheet. When opening the action sheet the color of the slider line and the handles changes. Only the slider line between the handles doesn't change. When closing, the color changes back to the tint color that I had set, but I set a custom color for the handles and I don't want to use the tint color for the handles. 

Preferably, opening an action sheet shouldn't change the colors, but at the very least, the colors shouldn't permanently change after closing the action sheet.

**Comment by TomThorpe** [comment]
Hey! Apologies for the very late response! If you are still having this issue would you be able to please re-open this or submit a new issue, but include a quick sample project showing the problem? Thanks!
