### ISSUE TITLE
How to move labels position to bottom?

### ISSUE THREAD

**Issue by secret3579** [TomThorpe/TTRangeSlider#31]
I want set frame for selected value labels. Current, it in top. I want move labels to bottom.

**Comment by Elipasousa** [comment]
+1

**Comment by TomThorpe** [comment]
Hi,

It's a good idea but unfortunately it doesnt currently support this. If anyone wants to do a PR with the changes required for it I'll happily take a look :-)

**Comment by secret3579** [comment]
Thank you for support.
I resolved this by my idea.

**Comment by secret3579** [comment]
Hi guy,

Thank you for support.
I resolved this by my idea.

Best and regards,
Huy Nguyen

2016-11-27 20:20 GMT+07:00 Tom Thorpe <notifications@github.com>:
