### ISSUE TITLE
Vertical position and change label

### ISSUE THREAD

**Issue by moon4ik** [TomThorpe/TTRangeSlider#40]
1. When I try to rotate Slider from horizontal to vertical position, it is stop working. 
    Perhaps it depends from gesture recognizer?

2. I want to change label and add % or some other value. How can I do that?

PS. Thanks a lot for the great work and TTRangeSlider.

**Comment by TomThorpe** [comment]
Hi,

For point 1 do you have an example project showing the issue please? I dont think anyone else has reported this problem. Please reopen this issue if you have one :-)

For point 2, you could probably look at the `numberFormatterOverride` property - it allows you to specify your own number formatter for the labels, which you could use to include the % symbol.
