### ISSUE TITLE
BUG: minLabel does not reappear after re-enabling range.

### ISSUE THREAD

**Issue by andrewbellay** [TomThorpe/TTRangeSlider#57]
First off, thanks for a very nice project. Secondly, I could see this being a low priority since it might be a bit of an edge case.

My use case involves another UI element that toggles on and off the range functionality of TTRangeSlider. Think of a switch that just toggles the disableRange property of TTRangeSlider.

**Repro Steps:**
1) Setup TTRangeSlider with the disableRange left at the defaults value of false.
2) Set disableRange to true.
3) Set disableRange back to false.

**What happens:**
The min handle reappears but the minLabel does not.

**Comment by TomThorpe** [comment]
Fixed in #58 - Thanks!
