### ISSUE TITLE
 TTRangeSlider not work in Swift

### ISSUE THREAD

**Issue by ahmadabudawod** [TomThorpe/TTRangeSlider#59]
I tried to import TTRangeSlider in my Swift project but unfortunately not work. Give error the file for TTRangeSlider.h not found in Bridge Header

**Comment by kiroskirin** [comment]
@ahmadabudawod Try this

Download this repo and drag 3 files from Pod/Classes/ to your project

```
TTRangeSlider.h
TTRangeSlider.m
TTRangeSliderDelegate.h
```

and Bridge Header file

```
#ifndef BridgingHeader_h
#define BridgingHeader_h

#import "TTRangeSlider.h"

#endif /* BridgingHeader_h */
```

Do this it work for me.

**Comment by TomThorpe** [comment]
Thanks kiroskirin! 

ahmadabudawod, please re-open if the above doesnt work :-)
