### ISSUE TITLE
initialState problem

### ISSUE THREAD

**Issue by mutlucicek** [TomThorpe/TTRangeSlider#7]
Hi... I am using TTRangeSlider in my app. I am instering the state of the TTrangeslider (min, max) to a table in FMDB in order to preserve its state whenever the users open the app again...
However, I am having problem with it. The delegate always update it to 10,90.. I checked the TTRangeSlider.m file and in that class, u set these values as selectedmin and selectedmax in initialiseControl method.
Now i ask that how could i request an sql selection in TTRanfeSlider class and set the selectedmin and selectedmax values to the values in the table?
Thanks

**Comment by TomThorpe** [comment]
Hi,

Thanks for reporting that. I've fixed the bug where the delegate was notified in f17eccb44077a575d23e7a63d606338ec8f4a689. The Delegate is only notified now as a result of user interaction. Can you try getting the latest from git and give it a try (I haven't pushed a new version to cocoapods yet, so if you're using cocoapods you'll have to point it directly to this repo)

I'm not entirely sure what you mean by your last question. Just remember to always try and set the values before the control is displayed

Thanks,
Tom
