### ISSUE TITLE
Looking forward to extend different background color.

### ISSUE THREAD

**Issue by Rain-dew** [TomThorpe/TTRangeSlider#70]
For example, red slider in the middle area,other gray

**Comment by henrique2601** [comment]
+1 , I need white in midle and other gray.

**Comment by redcapua** [comment]
Hi!

@Rain-dew @henrique2601 

There is property `sliderLineBetweenHandles` to set color between sliders.

**Comment by Rain-dew** [comment]
Thank you！ I'll try.




| |
zhangyuluios
邮箱：zhangyuluios@163.com
|

Signature is customized by Netease Mail Master

On 12/05/2018 03:38, Vladimir Samoylenko wrote:

Hi!

@Rain-dew@henrique2601

There is property sliderLineBetweenHandles to set color between sliders.
