### ISSUE TITLE
Urgent Question

### ISSUE THREAD

**Issue by amjadmansor** [TomThorpe/TTRangeSlider#75]
hello thank you for this good library but i have question possible to set min value on right side and max value on the left side ?

Best Regards

**Comment by TomThorpe** [comment]
Hi! There’s not really a native way to do this, but the only way I could think of that you could get around it would be to set it up normally (with min value and max value), then behind the scenes change the number formatters using the number formatter override, and the logic of the selected values to basically emulate this functionality.
