### ISSUE TITLE
Feature Request: Customize label for min and maximum value

### ISSUE THREAD

**Issue by superdev89** [TomThorpe/TTRangeSlider#78]
Can I customize the label for the maximum value?

For example, I'd like to put label 'No limit' for maximum value if user drags to maximum and treat only min value in this case.

**Comment by TomThorpe** [comment]
Hi!

I think your best bet is extending NSNumberFormatter, and implementing stringForObjectValue so that if the value = maxvalue of the slider, it adds whatever text you want.

Then set that as the `numberFormatterOverride` property
