### ISSUE TITLE
Install through cocoapods will not have minDistance/maxDistance/step options

### ISSUE THREAD

**Issue by DesmondPang** [TomThorpe/TTRangeSlider#8]
Install through cocoapod will not have minDistance/maxDistance options. But the cocapods indicated the installed version is 1.0.2. It seems that the files from cocoapods are not same as the github. Please advise it. Thanks

**Comment by TomThorpe** [comment]
Hey,

The latest released version was 1.0.2, which didn't have these additions yet. I've just released version 1.0.3 though so you should be able to do a pod update and get them now :-)

Thanks,
Tom

**Comment by DesmondPang** [comment]
Thank you so much.

**Comment by TomThorpe** [comment]
No problem - thanks for using TTRangeSlider :-)
