### ISSUE TITLE
TTRangeSliderDelegate It not Working

### ISSUE THREAD

**Issue by erishiraj** [TomThorpe/TTRangeSlider#86]
How to get Min Max Value at the Sliding time please help me
I have to try this by using below code but it's never called...

```
public func rangeSlider(_ sender: TTRangeSlider!, didChangeSelectedMinimumValue selectedMinimum: Float, andMaximumValue selectedMaximum: Float) {
print(selectedMinimum)
print(selectedMaximum)
// updateLabelsValues(selectedMinimum, max: selectedMaximum)
}
```
And I have Also Extent my class by **`TTRangeSliderDelegate`**

Thanks in Advance.

**Comment by erishiraj** [comment]
How to get Min Max Value at the Sliding time please help me
I have to try this by using below code but it's never called...

>    public func rangeSlider(_ sender: TTRangeSlider!, didChangeSelectedMinimumValue selectedMinimum: Float, andMaximumValue selectedMaximum: Float) {
        print(selectedMinimum)
        print(selectedMaximum)
       // updateLabelsValues(selectedMinimum, max: selectedMaximum)
    }

**Comment by redcapua** [comment]
@erishiraj 

Hi!

maxValue and minValue are properties of sender object.

**Comment by TomThorpe** [comment]
Thanks @redcapua!
