### ISSUE TITLE
Wrong font on iOS 13

### ISSUE THREAD

**Issue by tdimeco** [TomThorpe/TTRangeSlider#99]
Hi,

There is a small issue on iOS 13 GM: The font of the min/max labels seems to be set to Times New Roman instead of the system default one, San Francisco.

iOS 12:
![ios-12](https://user-images.githubusercontent.com/3112087/64734060-32b80c80-d4e6-11e9-875b-692aa93198d4.png)

iOS 13:
![ios-13](https://user-images.githubusercontent.com/3112087/64734063-3481d000-d4e6-11e9-8517-fbeff4d07f7f.png)

Using `rangeSlider.minLabelFont` or `rangeSlider.maxLabelFont` has no effect.

Also, the console prints the following message:

```
CoreText performance note: Client called CTFontCreateWithName() using name ".SFUI-Regular" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.
CoreText performance note: Set a breakpoint on CTFontLogSuboptimalRequest to debug.
```

Thank you.

**Comment by ghubaddole** [comment]
+1

**Comment by immago** [comment]
Fix: remove .fontName


```
-(void)setMinLabelFont:(UIFont *)minLabelFont{
    _minLabelFont = minLabelFont;
    self.minLabel.font = (__bridge CFTypeRef)_minLabelFont;
    self.minLabel.fontSize = _minLabelFont.pointSize;
}

-(void)setMaxLabelFont:(UIFont *)maxLabelFont{
    _maxLabelFont = maxLabelFont;
    self.maxLabel.font = (__bridge CFTypeRef)_maxLabelFont;
    self.maxLabel.fontSize = _maxLabelFont.pointSize;
}
```

**Comment by TomThorpe** [comment]
Thanks - If people can confirm this works and someone wants to PR it I'll be happy to approve it 👍

**Comment by tdimeco** [comment]
`CATextLayer.font` [documentation prohibits the use](https://developer.apple.com/documentation/quartzcore/catextlayer/1515303-font?language=objc) of `UIFont`. But it actually seems to work. However, in the sample Demo, the `$` character is missing in iOS 13. Maybe it's related to the use of `UIFont`?

iOS 12
<img width="369" alt="iOS 12" src="https://user-images.githubusercontent.com/3112087/66987625-6e378f00-f0c1-11e9-918b-349b861e4b12.png">

iOS 13
<img width="367" alt="iOS 13" src="https://user-images.githubusercontent.com/3112087/66987645-755e9d00-f0c1-11e9-984e-f4b83b2fd6c3.png">

**Comment by tdimeco** [comment]
The missing `$` caracter is actually an issue with the iOS simulator, so forget about it ;)

**Comment by Alasker** [comment]
> Thanks - If people can confirm this works and someone wants to PR it I'll be happy to approve it 👍

Tested on iPhoneXr running iOS13.3.1. Problem visible before the fix, gone after applying it.

**Comment by TomThorpe** [comment]
Thanks - I’ve merged that PR

**Comment by tdimeco** [comment]
Thanks! :-) Maybe a `1.0.7` version should be released?
